/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const NextEvent = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'estimatedDate' : IDL.Text,
});
export const AnticipationAnalysis = IDL.Record({
  'historicalPatternSummary' : IDL.Text,
  'expectedMaxMultiplier' : IDL.Float64,
  'expectedMinMultiplier' : IDL.Float64,
  'nextEvent' : NextEvent,
  'summary' : IDL.Text,
});
export const SimilarPeriod = IDL.Record({
  'endDate' : IDL.Text,
  'period' : IDL.Text,
  'description' : IDL.Text,
  'priceChangePercent' : IDL.Float64,
  'startDate' : IDL.Text,
});
export const ContextAnalysis = IDL.Record({
  'mostSimilarPeriod' : SimilarPeriod,
  'percentFromATH' : IDL.Float64,
  'cyclePhase' : IDL.Text,
  'daysSinceLastHalving' : IDL.Nat,
  'keySummary' : IDL.Text,
});
export const EventStats = IDL.Record({
  'totalEvents' : IDL.Nat,
  'halvings' : IDL.Nat,
  'crises' : IDL.Nat,
  'macroEvents' : IDL.Nat,
  'fedEvents' : IDL.Nat,
});
export const EventType = IDL.Variant({
  'macro' : IDL.Null,
  'halving' : IDL.Null,
  'fedEvent' : IDL.Null,
  'crisis' : IDL.Null,
});
export const Event = IDL.Record({
  'id' : IDL.Nat,
  'title' : IDL.Text,
  'priceAtEvent' : IDL.Float64,
  'date' : IDL.Text,
  'priceImpactPercent' : IDL.Float64,
  'description' : IDL.Text,
  'eventType' : EventType,
});
export const PricePoint = IDL.Record({
  'date' : IDL.Text,
  'volume' : IDL.Float64,
  'price' : IDL.Float64,
});

export const idlService = IDL.Service({
  'analyzeAnticipation' : IDL.Func([], [AnticipationAnalysis], ['query']),
  'analyzeCurrentContext' : IDL.Func([], [ContextAnalysis], ['query']),
  'getEventStats' : IDL.Func([], [EventStats], ['query']),
  'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
  'getPriceWindow' : IDL.Func(
      [IDL.Text, IDL.Text],
      [IDL.Vec(PricePoint)],
      ['query'],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const NextEvent = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'estimatedDate' : IDL.Text,
  });
  const AnticipationAnalysis = IDL.Record({
    'historicalPatternSummary' : IDL.Text,
    'expectedMaxMultiplier' : IDL.Float64,
    'expectedMinMultiplier' : IDL.Float64,
    'nextEvent' : NextEvent,
    'summary' : IDL.Text,
  });
  const SimilarPeriod = IDL.Record({
    'endDate' : IDL.Text,
    'period' : IDL.Text,
    'description' : IDL.Text,
    'priceChangePercent' : IDL.Float64,
    'startDate' : IDL.Text,
  });
  const ContextAnalysis = IDL.Record({
    'mostSimilarPeriod' : SimilarPeriod,
    'percentFromATH' : IDL.Float64,
    'cyclePhase' : IDL.Text,
    'daysSinceLastHalving' : IDL.Nat,
    'keySummary' : IDL.Text,
  });
  const EventStats = IDL.Record({
    'totalEvents' : IDL.Nat,
    'halvings' : IDL.Nat,
    'crises' : IDL.Nat,
    'macroEvents' : IDL.Nat,
    'fedEvents' : IDL.Nat,
  });
  const EventType = IDL.Variant({
    'macro' : IDL.Null,
    'halving' : IDL.Null,
    'fedEvent' : IDL.Null,
    'crisis' : IDL.Null,
  });
  const Event = IDL.Record({
    'id' : IDL.Nat,
    'title' : IDL.Text,
    'priceAtEvent' : IDL.Float64,
    'date' : IDL.Text,
    'priceImpactPercent' : IDL.Float64,
    'description' : IDL.Text,
    'eventType' : EventType,
  });
  const PricePoint = IDL.Record({
    'date' : IDL.Text,
    'volume' : IDL.Float64,
    'price' : IDL.Float64,
  });
  
  return IDL.Service({
    'analyzeAnticipation' : IDL.Func([], [AnticipationAnalysis], ['query']),
    'analyzeCurrentContext' : IDL.Func([], [ContextAnalysis], ['query']),
    'getEventStats' : IDL.Func([], [EventStats], ['query']),
    'getEvents' : IDL.Func([], [IDL.Vec(Event)], ['query']),
    'getPriceWindow' : IDL.Func(
        [IDL.Text, IDL.Text],
        [IDL.Vec(PricePoint)],
        ['query'],
      ),
  });
};

export const init = ({ IDL }) => { return []; };