/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface AnticipationAnalysis {
  'historicalPatternSummary' : string,
  'expectedMaxMultiplier' : number,
  'expectedMinMultiplier' : number,
  'nextEvent' : NextEvent,
  'summary' : string,
}
export interface ContextAnalysis {
  'mostSimilarPeriod' : SimilarPeriod,
  'percentFromATH' : number,
  'cyclePhase' : string,
  'daysSinceLastHalving' : bigint,
  'keySummary' : string,
}
export interface Event {
  'id' : bigint,
  'title' : string,
  'priceAtEvent' : number,
  'date' : string,
  'priceImpactPercent' : number,
  'description' : string,
  'eventType' : EventType,
}
export interface EventStats {
  'totalEvents' : bigint,
  'halvings' : bigint,
  'crises' : bigint,
  'macroEvents' : bigint,
  'fedEvents' : bigint,
}
export type EventType = { 'macro' : null } |
  { 'halving' : null } |
  { 'fedEvent' : null } |
  { 'crisis' : null };
export interface NextEvent {
  'title' : string,
  'description' : string,
  'estimatedDate' : string,
}
export interface PricePoint {
  'date' : string,
  'volume' : number,
  'price' : number,
}
export interface SimilarPeriod {
  'endDate' : string,
  'period' : string,
  'description' : string,
  'priceChangePercent' : number,
  'startDate' : string,
}
export interface _SERVICE {
  'analyzeAnticipation' : ActorMethod<[], AnticipationAnalysis>,
  'analyzeCurrentContext' : ActorMethod<[], ContextAnalysis>,
  'getEventStats' : ActorMethod<[], EventStats>,
  'getEvents' : ActorMethod<[], Array<Event>>,
  'getPriceWindow' : ActorMethod<[string, string], Array<PricePoint>>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];